services:
  nginx:
    image: nginx:1.31.1-alpine3.23-slim
    container_name: auditor-nginx
    environment:
      - TZ=Asia/Taipei
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      auditor:
        condition: service_started
    restart: unless-stopped

  auditor:
    build: .
    container_name: auditor-app
    environment:
      - TZ=Asia/Taipei
    env_file:
      - .env
    volumes:
      - ./reports:/app/reports
    expose:
      - "8000"
    restart: unless-stopped
